/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HealthStateDto } from '../../models/health-state-dto';

export interface HealthControllerGetHealth$Params {
}

export function healthControllerGetHealth(http: HttpClient, rootUrl: string, params?: HealthControllerGetHealth$Params, context?: HttpContext): Observable<StrictHttpResponse<HealthStateDto>> {
  const rb = new RequestBuilder(rootUrl, healthControllerGetHealth.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HealthStateDto>;
    })
  );
}

healthControllerGetHealth.PATH = '/api/health';
