/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActivePatchDto } from '../../models/active-patch-dto';
import { TodoReturnDto } from '../../models/todo-return-dto';

export interface AdminTodoTableControllerReplaceActiveFlagForTable$Params {

/**
 * Wir verwenden GUIDs als IDs für unsere Stammdaten und hiermit wird der Datensatz eindeutig identifiziert<ul/>
 */
  guid: string;
  
    /**
     * Setz nur das Active Flag.
     */
    body: ActivePatchDto
}

export function adminTodoTableControllerReplaceActiveFlagForTable(http: HttpClient, rootUrl: string, params: AdminTodoTableControllerReplaceActiveFlagForTable$Params, context?: HttpContext): Observable<StrictHttpResponse<TodoReturnDto>> {
  const rb = new RequestBuilder(rootUrl, adminTodoTableControllerReplaceActiveFlagForTable.PATH, 'patch');
  if (params) {
    rb.path('guid', params.guid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TodoReturnDto>;
    })
  );
}

adminTodoTableControllerReplaceActiveFlagForTable.PATH = '/api/todo/admin/{guid}';
