/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TodoReturnDto } from '../../models/todo-return-dto';

export interface AdminTodoTableControllerDeleteEntryForTable$Params {

/**
 * Wir verwenden GUIDs als IDs für unsere Stammdaten und hiermit wird der Datensatz eindeutig identifiziert<ul/>
 */
  guid: string;
}

export function adminTodoTableControllerDeleteEntryForTable(http: HttpClient, rootUrl: string, params: AdminTodoTableControllerDeleteEntryForTable$Params, context?: HttpContext): Observable<StrictHttpResponse<TodoReturnDto>> {
  const rb = new RequestBuilder(rootUrl, adminTodoTableControllerDeleteEntryForTable.PATH, 'delete');
  if (params) {
    rb.path('guid', params.guid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TodoReturnDto>;
    })
  );
}

adminTodoTableControllerDeleteEntryForTable.PATH = '/api/todo/admin/{guid}';
