/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TodoReturnDto } from '../../models/todo-return-dto';

export interface TodoTableControllerGetAllForTable$Params {

/**
 * Je nach Recht kann man so auch inaktive Datensätze anzeigen!
 */
  showAll?: boolean;
}

export function todoTableControllerGetAllForTable(http: HttpClient, rootUrl: string, params?: TodoTableControllerGetAllForTable$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TodoReturnDto>>> {
  const rb = new RequestBuilder(rootUrl, todoTableControllerGetAllForTable.PATH, 'get');
  if (params) {
    rb.query('showAll', params.showAll, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TodoReturnDto>>;
    })
  );
}

todoTableControllerGetAllForTable.PATH = '/api/todo/data';
