/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TodoReturnDto } from '../../models/todo-return-dto';

export interface TodoTableControllerGetOneTableEntry$Params {

/**
 * Je nach Recht kann man so auch inaktive Datensätze anzeigen!
 */
  showAll?: boolean;

/**
 * Wir verwenden GUIDs als IDs für unsere Stammdaten und hiermit wird der Datensatz eindeutig identifiziert<ul/>
 */
  guid: string;
}

export function todoTableControllerGetOneTableEntry(http: HttpClient, rootUrl: string, params: TodoTableControllerGetOneTableEntry$Params, context?: HttpContext): Observable<StrictHttpResponse<TodoReturnDto>> {
  const rb = new RequestBuilder(rootUrl, todoTableControllerGetOneTableEntry.PATH, 'get');
  if (params) {
    rb.query('showAll', params.showAll, {});
    rb.path('guid', params.guid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TodoReturnDto>;
    })
  );
}

todoTableControllerGetOneTableEntry.PATH = '/api/todo/data/{guid}';
