/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TodoCreateDto } from '../../models/todo-create-dto';
import { TodoReturnDto } from '../../models/todo-return-dto';

export interface TodoTableControllerCreateEntryForTable$Params {
  
    /**
     * Neues todo item anlegen!
     */
    body: TodoCreateDto
}

export function todoTableControllerCreateEntryForTable(http: HttpClient, rootUrl: string, params: TodoTableControllerCreateEntryForTable$Params, context?: HttpContext): Observable<StrictHttpResponse<TodoReturnDto>> {
  const rb = new RequestBuilder(rootUrl, todoTableControllerCreateEntryForTable.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TodoReturnDto>;
    })
  );
}

todoTableControllerCreateEntryForTable.PATH = '/api/todo/data';
