/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { HealthControllerGetHealth$Params as HealthControllerGetHealth$Params } from './fn/health/health-controller-get-health';
export { healthControllerGetHealth as healthControllerGetHealth } from './fn/health/health-controller-get-health';
export type { TodoTableControllerGetAllForTable$Params as TodoTableControllerGetAllForTable$Params } from './fn/todo-user/todo-table-controller-get-all-for-table';
export { todoTableControllerGetAllForTable as todoTableControllerGetAllForTable } from './fn/todo-user/todo-table-controller-get-all-for-table';
export type { TodoTableControllerCreateEntryForTable$Params as TodoTableControllerCreateEntryForTable$Params } from './fn/todo-user/todo-table-controller-create-entry-for-table';
export { todoTableControllerCreateEntryForTable as todoTableControllerCreateEntryForTable } from './fn/todo-user/todo-table-controller-create-entry-for-table';
export type { TodoTableControllerGetOneTableEntry$Params as TodoTableControllerGetOneTableEntry$Params } from './fn/todo-user/todo-table-controller-get-one-table-entry';
export { todoTableControllerGetOneTableEntry as todoTableControllerGetOneTableEntry } from './fn/todo-user/todo-table-controller-get-one-table-entry';
export type { TodoTableControllerReplaceEntryForTable$Params as TodoTableControllerReplaceEntryForTable$Params } from './fn/todo-user/todo-table-controller-replace-entry-for-table';
export { todoTableControllerReplaceEntryForTable as todoTableControllerReplaceEntryForTable } from './fn/todo-user/todo-table-controller-replace-entry-for-table';
export type { AdminTodoTableControllerDeleteEntryForTable$Params as AdminTodoTableControllerDeleteEntryForTable$Params } from './fn/todo-admin/admin-todo-table-controller-delete-entry-for-table';
export { adminTodoTableControllerDeleteEntryForTable as adminTodoTableControllerDeleteEntryForTable } from './fn/todo-admin/admin-todo-table-controller-delete-entry-for-table';
export type { AdminTodoTableControllerReplaceActiveFlagForTable$Params as AdminTodoTableControllerReplaceActiveFlagForTable$Params } from './fn/todo-admin/admin-todo-table-controller-replace-active-flag-for-table';
export { adminTodoTableControllerReplaceActiveFlagForTable as adminTodoTableControllerReplaceActiveFlagForTable } from './fn/todo-admin/admin-todo-table-controller-replace-active-flag-for-table';
