/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ActivePatchDto } from './models/active-patch-dto';
export type { DatabaseOptionsDto } from './models/database-options-dto';
export type { HealthStateDto } from './models/health-state-dto';
export type { TodoCreateDto } from './models/todo-create-dto';
export type { TodoReturnDto } from './models/todo-return-dto';
export type { TodoUpdateDto } from './models/todo-update-dto';
