/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivePatchDto {

  /**
   * the field describes if the todo item is an active one.
   */
  active: boolean;
}
