/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DatabaseOptionsDto {

  /**
   * the message of the state
   */
  databaseName: string;

  /**
   * The array of supported entities
   */
  entities: Array<string>;

  /**
   * the used database type.
   */
  type: string;
}
