/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DatabaseOptionsDto } from '../models/database-options-dto';
export interface HealthStateDto {

  /**
   * Database Options
   */
  databaseOptions: DatabaseOptionsDto;

  /**
   * the message of the state
   */
  message: string;

  /**
   * Health state of the system. Either okay or error
   */
  state: string;

  /**
   * Api-Version
   */
  version: string;
}
